# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    must_be_immutable: ignore
    import_of_legacy_library_into_null_safe: ignore

linter:
  rules:
    avoid_print: false
    prefer_const_constructors: false
    prefer_single_quotes: false
    must_be_immutable: false
    prefer_function_declarations_over_variables: false
    prefer_typing_uninitialized_variables: false
    use_key_in_widget_constructors: false
    prefer_null_aware_operators: false
    unnecessary_null_comparison: false
    file_names: false
    non_constant_identifier_names: false
    unused_import: false
    prefer_const_constructors_in_immutables: false
    hash_and_equals: false
    import_of_legacy_library_into_null_safe: false

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
